export const TOGGLE_FILM = 'TOGGLE_FILM';
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const SELECT_FILM = 'SELECT_FILM';
export const LOADING_FILM = 'LOADING_FILM';
export const FILTER_FILMS = 'FILTER_FILMS';
export const ADD_TO_SEARCHLIST = 'ADD_TO_SEARCHLIST';
export const LOAD_PLAYLIST = 'LOAD_PLAYLIST';
export const LOAD_PLAYLIST_COMPLETE = 'LOAD_PLAYLIST_COMPLETE';

//User actions
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const TOGGLE_CHECK_AUTHENTICATION = "TOGGLE_CHECK_AUTHENTICATION";
  