export const TOGGLE_FILM = 'TOGGLE_FILM';
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const SELECT_FILM = 'SELECT_FILM';
export const LOADING_FILM = 'LOADING_FILM';
export const FILTER_FILMS = 'FILTER_FILMS';
export const ADD_TO_SEARCHLIST = 'ADD_TO_SEARCHLIST';
export const CLEAR_SEARCHLIST = 'CLEAR_SEARCHLIST';
export const SEARCHLIST_ERROR = 'SEARCHLIST_ERROR';
export const SELECT_SUGGESTED_FILM = 'SELECT_SUGGESTED_FILM';
  